"""
Seller Analysis MCP Tool.

Provides business capabilities related to seller
performance, revenue, and fulfillment quality.

The Data Intelligence Agent uses these functions
instead of generating SQL directly.
"""

from typing import Any

from mcp.tools.query_db import query_db
from utils.logger import logger


def seller_summary(user_id:int,mode: str = "historical"):
    """
    Retrieve overall seller statistics.
    """
    sql = """
    SELECT
        COUNT(DISTINCT seller_id) AS total_sellers,
        SUM(quantity) AS total_items_sold,
        ROUND(SUM(order_item_value)::numeric, 2) AS total_revenue
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.user_id = :user_id;
    """

    logger.info("Executing seller summary")

    try:
        return query_db(sql, {"user_id": user_id},mode)
    except Exception as exc:
        logger.exception(
            "Seller summary query failed: %s",
            exc,
        )
        raise RuntimeError(
            "Failed to retrieve seller summary."
        ) from exc


def top_sellers(user_id:int,limit: int = 10,mode: str = "historical"):
    """
    Retrieve top sellers by revenue.
    """
    limit = max(1, min(limit, 100))

    sql = f"""
    SELECT
        seller_id,
        SUM(quantity) AS items_sold,
        ROUND(SUM(order_item_value)::numeric, 2) AS revenue
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.user_id = :user_id
    GROUP BY seller_id
    ORDER BY revenue DESC
    LIMIT {limit};
    """

    logger.info("Executing top sellers")

    try:
        return query_db(sql, {"user_id": user_id},mode)
    except Exception as exc:
        logger.exception(
            "Top sellers query failed: %s",
            exc,
        )
        raise RuntimeError(
            "Failed to retrieve top sellers."
        ) from exc


def seller_revenue(user_id:int,mode: str = "historical"):
    """
    Retrieve revenue generated by each seller.
    """
    sql = """
    SELECT
        seller_id,
        ROUND(SUM(order_item_value)::numeric, 2) AS revenue
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.user_id = :user_id
    GROUP BY seller_id
    ORDER BY revenue DESC;
    """

    logger.info("Executing seller revenue")

    try:
        return query_db(sql,{"user_id": user_id}, mode)
    except Exception as exc:
        logger.exception(
            "Seller revenue query failed: %s",
            exc,
        )
        raise RuntimeError(
            "Failed to retrieve seller revenue."
        ) from exc


def seller_delivery_performance(user_id:int,mode: str = "historical"):
    """
    Retrieve delivery performance by seller.
    """
    sql = """
    SELECT
        oi.seller_id,

        COUNT(*) AS total_orders,

        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM (
                        o.delivered_date - o.order_date
                    )
                ) / 86400
            )::numeric,
            2
        ) AS average_delivery_days,

        SUM(
            CASE
                WHEN o.delivered_date >
                     o.estimated_delivery_date
                THEN 1
                ELSE 0
            END
        ) AS late_deliveries

    FROM order_items oi

    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.delivered_date IS NOT NULL

    AND o.user_id = :user_id

    GROUP BY oi.seller_id

    ORDER BY late_deliveries DESC;
    """

    logger.info("Executing seller delivery performance")

    try:
        return query_db(sql,{"user_id": user_id}, mode)
    except Exception as exc:
        logger.exception(
            "seller delivery performance query failed: %s",
            exc,
        )
        raise RuntimeError(
            "Failed to retrieve seller delivery performance."
        ) from exc


def sellers_by_state(user_id:int,mode: str = "historical"):
    """
    Retrieve seller distribution by state.
    """
    sql = """
    SELECT
        seller_state,
        COUNT(*) AS total_sellers
    FROM sellers
    WHERE user_id = :user_id
    GROUP BY seller_state
    ORDER BY total_sellers DESC;
    """

    logger.info("Executing sellers by state")

    try:
        return query_db(sql, {"user_id": user_id},mode)
    except Exception as exc:
        logger.exception(
            "sellers by state query failed: %s",
            exc,
        )
        raise RuntimeError(
            "Failed to retrieve sellers by state."
        ) from exc