"""
Seller Analysis MCP Tool.

Provides business capabilities related to seller
performance, revenue, and fulfillment quality.

The Data Intelligence Agent uses these functions
instead of generating SQL directly.
"""

from typing import Any

from mcp.tools.query_db import query_db
from utils.logger import logger


def seller_summary(mode: str = "historical"):
    """
    Retrieve overall seller statistics.
    """
    sql = """
    SELECT
        COUNT(DISTINCT seller_id) AS total_sellers,
        COUNT(*) AS total_items_sold,
        ROUND(SUM(price), 2) AS total_revenue
    FROM order_items;
    """

    logger.info("Executing seller summary")

    return query_db(sql, mode)


def top_sellers(limit: int = 10,mode: str = "historical"):
    """
    Retrieve top sellers by revenue.
    """
    limit = max(1, min(limit, 100))

    sql = f"""
    SELECT
        seller_id,
        COUNT(*) AS items_sold,
        ROUND(SUM(price), 2) AS revenue
    FROM order_items
    GROUP BY seller_id
    ORDER BY revenue DESC
    LIMIT {limit};
    """

    logger.info("Executing top sellers")

    return query_db(sql, mode)


def seller_revenue(mode: str = "historical"):
    """
    Retrieve revenue generated by each seller.
    """
    sql = """
    SELECT
        seller_id,
        ROUND(SUM(price), 2) AS revenue
    FROM order_items
    GROUP BY seller_id
    ORDER BY revenue DESC;
    """

    logger.info("Executing seller revenue")

    return query_db(sql, mode)


def seller_delivery_performance(mode: str = "historical"):
    """
    Retrieve delivery performance by seller.
    """
    sql = """
    SELECT
        oi.seller_id,

        COUNT(*) AS total_orders,

        ROUND(
            AVG(
                julianday(o.order_delivered_customer_date) -
                julianday(o.order_purchase_timestamp)
            ),
            2
        ) AS average_delivery_days,

        SUM(
            CASE
                WHEN o.order_delivered_customer_date >
                     o.order_estimated_delivery_date
                THEN 1
                ELSE 0
            END
        ) AS late_deliveries

    FROM order_items oi

    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.order_delivered_customer_date IS NOT NULL

    GROUP BY oi.seller_id

    ORDER BY late_deliveries DESC;
    """

    logger.info("Executing seller delivery performance")

    return query_db(sql, mode)


def sellers_by_state(mode: str = "historical"):
    """
    Retrieve seller distribution by state.
    """
    sql = """
    SELECT
        seller_state,
        COUNT(*) AS total_sellers
    FROM sellers
    GROUP BY seller_state
    ORDER BY total_sellers DESC;
    """

    logger.info("Executing sellers by state")

    return query_db(sql, mode)