"""
Executive recommendation service.

Provides database operations for storing,
retrieving, and deleting executive recommendations.
"""
from datetime import timezone

from sqlalchemy.orm import Session
from utils.logger import logger
from database.database import SessionLocal
from database.models import ExecutiveRecommendation
import json
from schemas.executive import ExecutiveAnalysis


class ExecutiveRecommendationService:
    """
    Service for managing executive recommendations.
    """


    def delete_all(self,user_id:int):
        """
        Remove all existing recommendations.
        """
        logger.info("Deleting executive recommendations.")
        
        db = SessionLocal()
        try:
            (db.query(ExecutiveRecommendation)
            .filter(ExecutiveRecommendation.user_id==user_id)
            .delete())
            db.commit()

            logger.info("Executive recommendations deleted.")
        except Exception as exc:
            db.rollback()
            logger.exception(
                "Failed to delete executive recommendations."
            )
            raise RuntimeError(
                "Unable to delete executive recommendations."
            ) from exc
        finally:
            db.close()
        
    def get_recommendations(self,user_id:int):
        """
        Return the latest executive report.
        """
        db = SessionLocal()
        logger.info("Fetching executive recommendations.")
        try:
            recommendations=(db.query(ExecutiveRecommendation)
                             .filter(ExecutiveRecommendation.user_id==user_id)
                             .order_by(ExecutiveRecommendation.created_at.desc()).all())
            if not recommendations:
                logger.info("No executive recommendations found.")
                return None
            
            first=recommendations[0]
            return {
                "executive_summary":first.executive_summary,
                "key_findings":json.loads(first.key_findings),
                "business_risks":json.loads(first.business_risks),
                "strategic_recommendations":[
                    {
                        "priority":r.priority,
                        "action":r.action,
                        "rationale":r.rationale,
                    }for r in recommendations
                ],
                "evidence":json.loads(first.evidence),
                "generated_at":first.created_at.replace(tzinfo=timezone.utc).isoformat(),
            }
        except Exception as exc:
            logger.exception(
                "Failed to retrieve executive recommendations."
            )
            raise RuntimeError(
                "Unable to retrieve executive recommendations."
            ) from exc

        finally:
            db.close()
    
    def save_recommendations(self, user_id:int,analysis: ExecutiveAnalysis):
        """
        Save executive recommendations.

        Deletes any existing recommendations and stores
        the newly generated executive analysis.

        Args:
            analysis: Executive analysis generated by the executive agent.

        Raises:
            RuntimeError:
                If recommendations cannot be saved.
        """

        db = SessionLocal()
        logger.info("Saving executive recommendations.")
        logger.info(
            "Saving %d recommendations",
            len(analysis.strategic_recommendations)
)

        try:

            db.query(ExecutiveRecommendation).delete()

            key_findings = json.dumps(analysis.key_findings)
            business_risks = json.dumps(analysis.business_risks)

            evidence = json.dumps([item.model_dump() for item in analysis.evidence])

            for recommendation in analysis.strategic_recommendations:
                logger.info(
                    "Saving recommendation: %s",
                    recommendation.action
                )
                record = ExecutiveRecommendation(
                    user_id=user_id,
                    priority=recommendation.priority,
                    action=recommendation.action,
                    rationale=recommendation.rationale,
                    executive_summary=analysis.executive_summary,
                    key_findings=key_findings,
                    business_risks=business_risks,
                    evidence=evidence,
                )

                db.add(record)

            db.commit()
            logger.info("Commit completed.")
            logger.info(
                "Saved %d strategic recommendations.",
                len(analysis.strategic_recommendations),
            )
        except Exception as exc:
            db.rollback()
            logger.exception(
                "Failed to save executive recommendations."
            )
            raise RuntimeError(
                "Unable to save executive recommendations."
            ) from exc

        finally:
            db.close()