version: 1.0

tables:

  customers:

    required: true

    primary_keys:
      - customer_id

    columns:

      customer_id:
        required: true
        dtype: string

      customer_unique_id:
        required: false
        dtype: string

      zip_code:
        required: false
        dtype: integer

      city:
        required: false
        dtype: string

      state:
        required: false
        dtype: string

  orders:

    required: true

    primary_keys:
      - order_id

    foreign_keys:

      customer_id:
        references:
          table: customers
          column: customer_id

    columns:

      order_id:
        required: true
        dtype: string

      customer_id:
        required: true
        dtype: string

      order_status:
        required: false
        dtype: string

      order_date:
        required: true
        dtype: datetime

      approved_date:
        required: false
        dtype: datetime

      carrier_delivery_date:
        required: false
        dtype: datetime

      delivered_date:
        required: false
        dtype: datetime

      estimated_delivery_date:
        required: false
        dtype: datetime

  products:

    required: true

    primary_keys:
      - product_id

    columns:

      product_id:
        required: true
        dtype: string

      category:
        required: false
        dtype: string

      product_name_length:
        required: false
        dtype: integer

      product_description_length:
        required: false
        dtype: integer

      photos_count:
        required: false
        dtype: integer

      weight:
        required: false
        dtype: float

      length:
        required: false
        dtype: float

      height:
        required: false
        dtype: float

      width:
        required: false
        dtype: float

  sellers:

    required: false

    primary_keys:
      - seller_id

    columns:

      seller_id:
        required: true
        dtype: string

      zip_code:
        required: false
        dtype: integer

      city:
        required: false
        dtype: string

      state:
        required: false
        dtype: string

  order_items:

    required: true

    primary_keys:
      - order_id
      - order_item_id

    foreign_keys:

      order_id:
        references:
          table: orders
          column: order_id

      product_id:
        references:
          table: products
          column: product_id

      seller_id:
        references:
          table: sellers
          column: seller_id

    columns:

      order_id:
        required: true
        dtype: string

      order_item_id:
        required: true
        dtype: string

      product_id:
        required: true
        dtype: string

      seller_id:
        required: false
        dtype: string

      shipping_limit_date:
        required: false
        dtype: datetime

      item_price:
        required: true
        dtype: float

      freight_cost:
        required: false
        dtype: float

  payments:

    required: true

    primary_keys:
      - order_id
      - payment_sequence

    foreign_keys:

      order_id:
        references:
          table: orders
          column: order_id

    columns:

      order_id:
        required: true
        dtype: string

      payment_sequence:
        required: true
        dtype: string

      payment_type:
        required: false
        dtype: string

      installments:
        required: false
        dtype: integer

      sales_amount:
        required: true
        dtype: float

  reviews:

    required: false

    primary_keys:
      - review_id

    foreign_keys:

      order_id:
        references:
          table: orders
          column: order_id

    columns:

      review_id:
        required: true
        dtype: string

      order_id:
        required: true
        dtype: string

      review_score:
        required: false
        dtype: integer

      review_title:
        required: false
        dtype: string

      review_text:
        required: true
        dtype: string

      review_creation_date:
        required: false
        dtype: datetime

      review_answer_date:
        required: false
        dtype: datetime

  geolocation:

    required: false

    primary_keys:
      - zip_code
      - latitude
      - longitude

    columns:

      zip_code:
        required: true
        dtype: integer

      latitude:
        required: true
        dtype: float

      longitude:
        required: true
        dtype: float

      city:
        required: false
        dtype: string

      state:
        required: false
        dtype: string

  category_translation:

    required: false

    primary_keys:
      - category

    columns:

      category:
        required: true
        dtype: string

      category_english:
        required: false
        dtype: string