orders:
  order_id: order_id
  customer_id: customer_id
  order_purchase_timestamp: order_date
  order_approved_at: approved_date
  order_delivered_carrier_date: carrier_delivery_date
  order_delivered_customer_date: delivered_date
  order_estimated_delivery_date: estimated_delivery_date

payments:
  order_id: order_id
  payment_sequential: payment_sequence
  payment_type: payment_type
  payment_installments: installments
  payment_value: sales_amount

products:
  product_id: product_id
  product_category_name: category
  product_name_lenght: product_name_length
  product_description_lenght: product_description_length
  product_photos_qty: photos_count
  product_weight_g: weight
  product_length_cm: length
  product_height_cm: height
  product_width_cm: width

customers:
  customer_id: customer_id
  customer_unique_id: customer_unique_id
  customer_zip_code_prefix: zip_code
  customer_city: city
  customer_state: state

reviews:
  review_id: review_id
  order_id: order_id
  review_score: review_score
  review_comment_title: review_title
  review_comment_message: review_text
  review_creation_date: review_creation_date
  review_answer_timestamp: review_answer_date

sellers:
  seller_id: seller_id
  seller_zip_code_prefix: zip_code
  seller_city: city
  seller_state: state

order_items:
  order_id: order_id
  order_item_id: order_item_id
  product_id: product_id
  seller_id: seller_id
  shipping_limit_date: shipping_limit_date
  price: item_price
  freight_value: freight_cost

geolocation:
  geolocation_zip_code_prefix: zip_code
  geolocation_lat: latitude
  geolocation_lng: longitude
  geolocation_city: city
  geolocation_state: state

category_translation:
  product_category_name: category
  product_category_name_english: category_english

#==================
# customers:

#   customer_id: customer_id
#   city: city
#   state: state
#   pincode: zip_code

# orders:

#   order_id: order_id
#   customer_id: customer_id
#   order_status: order_status
#   order_date: order_date

# products:

#   product_id: product_id

# payments:

#   order_id: order_id
#   payment_method: payment_type
#   payment_amount_inr: sales_amount

# reviews:

#   review_id: review_id
#   order_id: order_id
#   rating: review_score
#   review_title: review_title
#   review_text: review_text
#   review_date: review_creation_date

# sellers:

#   seller_id: seller_id
#   city: city
#   state: state

# order_items:

#   order_id: order_id
#   order_item_id: order_item_id
#   product_id: product_id
#   seller_id: seller_id
#   unit_price_inr: item_price
#   freight_cost_inr: freight_cost

# categories:

#   category_name: category

# deliveries:

#   estimated_delivery_date: estimated_delivery_date
#   actual_delivery_date: delivered_date
  #------------------------------------------------