dataset:
  name: olist
  connector: csv
  raw_path: data/raw

validation:

  required_tables:
    - customers
    - orders
    - order_items
    - products
    - payments

  optional_tables:
    - reviews
    - sellers
    - geolocation
    - category_translation

tables:

  customers:
    enabled: true
    file: olist_customers_dataset.csv
    primary_keys:
      - customer_id

  orders:
    enabled: true
    file: olist_orders_dataset.csv
    primary_keys:
      - order_id

  order_items:
    enabled: true
    file: olist_order_items_dataset.csv
    primary_keys:
      - order_id
      - order_item_id

  payments:
    enabled: true
    file: olist_order_payments_dataset.csv
    primary_keys:
      - order_id
      - payment_sequential

  products:
    enabled: true
    file: olist_products_dataset.csv
    primary_keys:
      - product_id

  sellers:
    enabled: true
    file: olist_sellers_dataset.csv
    primary_keys:
      - seller_id

  reviews:
    enabled: true
    file: olist_order_reviews_dataset.csv
    primary_keys:
      - review_id

  geolocation:
    enabled: true
    file: olist_geolocation_dataset.csv
    primary_keys:
      - geolocation_zip_code_prefix
      - geolocation_lat
      - geolocation_lng

  category_translation:
    enabled: true
    file: product_category_name_translation.csv
    primary_keys:
      - product_name